#! /usr/bin/env ruby
## -*- mode: ruby -*-
## = scan individual_log and generate grid population map
## Author:: Itsuki Noda
## Version:: 0.0 2016/11/14 I.Noda
##
## === History
## * [2016/11/14]: Create This File.
## * [YYYY/MM/DD]: add more
## == Usage
## * ...

require 'optparse' ;
require 'pp' ;
require 'time' ;
require 'csv' ;

$toolBaseDir = File::dirname(__FILE__) ;

$LOAD_PATH.push("#{$toolBaseDir}/./RubyLib");

require 'WithConfParam' ;


#------------------------------------------------------------------------
#++
$conf = {
  :origin => [0.0, 0.0, 0.0],
  :gridSize => [500.0, 500.0, 5.0],
  :offset => [0.0, 0.0, 0.0],
  :timeStep => 60*60,
  :timeOrigin => "00:00:00",
  :outfile => nil,
  :fillP => false,
  :quietP => false,
} ;

#------------------------------------------------------------------------
#++
## scan X-Y or X-Y-Z value
def scanXYZ(xyz, destArray = nil)
  pos = xyz.split(":").map{|v| v.to_f} ;
  if(destArray.nil?) then
    return pos ;
  else
    if(pos.length == 3) then
      destArray[0,3] = pos[0,3] ;
    elsif(pos.length == 2) then
      destArray[0,2] = pos[0,2] ;
    else
      raise "XYZ format should be 'x.xx:y.yy' or 'x.xx:y.yy:z.zz'." ;
    end
    return destArray ;
  end
end
  
#------------------------------------------------------------------------
$op = OptionParser.new() {|op|
  op.banner = <<_END_
  Usage: #{$0} [Options]* <individual_pedestrian_log.log> 
  Scan CrowdWalk's individual_pedestrian_log and output grid populations.
  The output goes out stdout or file specified by -O option.
  The output format is csv file in the following columns:
	timeIndex, gridIndex_X, gridIndex_Y, gridIndex_Z, population
  The timeIndex is count of time step (default 3600sec) from "00:00:00".
  The gridIndex_XYZ starts from the origin [0,0,0] (or specified by -o option).
  The grid size is 500m in X and Y, and 5m in Z axis.
_END_

  op.separator("Options:") ;
  op.set_summary_indent("") ;
  op.set_summary_width(60) ;
  sep = "\n\t\t" ;

  op.on("-o","--origin X:Y", String, sep + "set origin in 'X:Y' or 'X:Y:Z' form..") {|xyz|
    scanXYZ(xyz, $conf[:origin]) ;
  }
  op.on("-g","--grid X:Y", String, sep + "set grid size in 'X:Y' or 'X:Y;Z' form.") {|xyz|
    scanXYZ(xyz, $conf[:gridSize]) ;
  }
  op.on("-s","--offset X:Y", String, sep + "set offset in 'X:Y' or 'X:Y:Z' form.") {|xyz|
    scanXYZ(xyz, $conf[:offset]) ;
  }
  op.on("-T","--timeOrigin Time", String, sep + "set time origin in 'HH:MM:SS' form.") {|time|
    $conf[:timeOrigin] = time ;
  }
  op.on("-t","--time Sec", Integer, sep + "set timeStep.") {|sec|
    $conf[:timeStep] = sec ;
  }
  op.on("-O","--output OutFile", String, sep + "output file.") {|outfile|
    $conf[:outfile] = outfile ;
  }
  op.on("-f","--fill", sep + "fill zero grid.") {
    $conf[:fillP] = true ;
  }
  op.on("-q","--quiet", sep + "suppress verbose outputs.") {
    $conf[:quietP] = true ;
  }
  op.on_tail("--help", sep + "show this message.") { |h|
    puts(op)
    exit(1)
  }
}

$op.parse!(ARGV) ;
$restArg = ARGV ;
if ($restArg.length < 1) then
  puts($op) ;
  exit(1) ;
end

p [:rest, ARGV], [:conf,$conf] if !$conf[:quietP] ;

#--======================================================================
#++
## Information of a grid
class Grid
  #--@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
  #++
  ## parent table
  attr_accessor :table ;
  ## index of the grid. [ix, iy, iz]
  attr_accessor :index ;
  ## time
  attr_accessor :time ;
  ## time index.
  attr_accessor :timeIndex ;
  ## list of agents
  attr_accessor :agentList ;
  ## population
  attr_accessor :population ;

  #--------------------------------------------------------------
  #++
  ## initialization.
  ## _table_:: parent table.
  ## _index_:: index in [ix, iy, iz] form
  ## _time_:: time index
  ## _timestr_:: a string to indicate time
  def initialize(table, index, time, timeIndex = nil)
    @table = table ;
    @index = index ;
    @time = time ;
    @timeIndex = timeIndex ;
    @population = 0 ;
    @agentList = [] ;
  end

  #--------------------------------------------------------------
  #++
  ## add agent
  ## _agent_:: id or agent object
  ## *return*:: current population
  def addAgent(agent)
#    @agentList.push(agent) ;
#    @population = @agentList.length ;
    incPopulation(1) ;
  end

  #--------------------------------------------------------------
  #++
  ## increment population
  ## _n_:: increment value
  ## *return*:: current population
  def incPopulation(n)
    @population += n ;
  end
  
  #--------------------------------------------------------------
  #++
  ## generate output data as an array
  ## _popUnit_:: normalize unit
  ## *return*:: array
  def genOutputArray(popUnit)
    normalizedPopulation = (@population.to_f / popUnit) ;
    return [@timeIndex,
            @index[0], @index[1], @index[2],
            normalizedPopulation]
  end
  
  #--------------------------------------------------------------
  #++
  ## generate output data as an array
  ## *return*:: array
  def genOutputLabelArray()
    return ["timeIndex",
            "posIndex_x", "posIndex_y", "posIndex_z",
            "population"] ;
  end

  #--============================================================
  #--::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
  #--@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
  #--------------------------------------------------------------
end # class Grid

#--======================================================================
#++
## collection of grids
class GridTable < WithConfParam
  #--::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
  #++
  ## default confitulation
  DefaultConf = { :origin => [0.0, 0.0, 0.0],
                  :gridSize => [500.0, 500.0, 5.0],
                  :offset => [0.0, 0.0, 0.0],
                  :timeStep => 60*60,
                  :timeOrigin => "00:00:00",
                  nil => nil } ;

  ## default confitulation
  DefaultDate = Time.parse("2000/01/01") ;

  ## required column name
  RequiredColumnName = ['pedestrianID',
                        'current_time',
                        'current_position_in_model_x',
                        'current_position_in_model_y',
                        'current_position_in_model_z',
                        'current_linkID',
                       ] ;

  #--@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
  #++
  ## origin. should be [x,y,z]
  attr_accessor :origin ;
  ## grid size. should be [x,y,z]
  attr_accessor :gridSize ;
  ## offset. should be [x,y,z]
  attr_accessor :offset ;
  ## timeStep
  attr_accessor :timeStep ;
  ## time origin. nil or "hh:mm:ss" or Time Object
  attr_accessor :timeOrigin ;
  ## time name table (map from time string to time object)
  attr_accessor :timeNameTable ;
  ## pos index table 
  attr_accessor :posIndexTable ;
  ## pos index list
  attr_accessor :posIndexList ;
  ## table of grid. [time, [ix,iy,iz]] => grid
  attr_accessor :gridTable ;
  ## table of summary grid. [timeIndex, [ix,iy,iz]] => grid
  attr_accessor :sumGridTable ;
  ## dummy grid for no data
  attr_accessor :dummyGrid ;
  
  #--------------------------------------------------------------
  #++
  ## initialize
  def initialize(conf = {})
    super(conf) ;
    @origin = getConf(:origin) ;
    @gridSize = getConf(:gridSize) ;
    @offset = getConf(:offset) ;
    @timeStep = getConf(:timeStep) ;
    @timeOrigin = getConf(:timeOrigin) ;
    @timeNameTable = {} ;
    @posIndexTable = {} ;
    @gridTable = {} ;
    @dummyGrid = Grid.new(self, nil, nil) ; 
    parseTimeOrigin(@timeOrigin) ;
  end
  
  #--------------------------------------------------------------
  #++
  ## get position index from position value
  def getPosIndex(pos)
    (x,y,z) = pos ;
    dx = x + @offset[0] - @origin[0] ;
    dy = y + @offset[1] - @origin[1] ;
    dz = z + @offset[2] - @origin[2] ;
    ix = (dx / @gridSize[0]).floor ;
    iy = (dy / @gridSize[1]).floor ;
    iz = (dz / @gridSize[2]).floor ;
    return [ix, iy, iz] ;
  end
    
  #--------------------------------------------------------------
  #++
  ## get position index from position value
  def getPosFromIndex(posIndex)
    (ix,iy,iz) = posIndex ;
    x = @origin[0] + ix * @gridSize[0] - @offset[0] ;
    y = @origin[1] + iy * @gridSize[1] - @offset[1] ;
    z = @origin[2] + iz * @gridSize[2] - @offset[2] ;
    return [x,y,z] ;
  end

  #--------------------------------------------------------------
  #++
  ## get position range index from position value.
  ## return [[x0, y0, z0],[x1, y1, z1]]
  def getPosRangeFromIndex(posIndex)
    beginPos = getPosFromIndex(posIndex)
    endPos = [beginPos[0] + @gridSize[0],
              beginPos[1] + @gridSize[1],
              beginPos[2] + @gridSize[2]] ;
    return [beginPos, endPos] 
  end

  #--------------------------------------------------------------
  #++
  ## parse time origin string
  def parseTimeOrigin(timeOrigin)
    @timeOrigin = parseTime(timeOrigin) ;
  end

  #--------------------------------------------------------------
  #++
  ## parse time string to Time object
  def parseTime(time)
    if(time.nil?)
      return nil ;
    elsif(time.is_a?(String))
      return Time.parse(time, DefaultDate) ;
    elsif(time.is_a?(Time))
      return time ;
    else
      raise "can not convert to Time Object from :" + time.inspect ;
    end
  end
  
  #--------------------------------------------------------------
  #++
  ## get time index
  def getTimeIndex(time)
    if(@timeOrigin.nil?) then
      return nil ;
    else
      time = parseTime(time) ;
      diff = time - @timeOrigin ;
      index = (diff / @timeStep).floor ;
      return index ;
    end
  end

  #--------------------------------------------------------------
  #++
  ## get time from index
  def getTimeFromIndex(index)
    if(@timeOrigin.nil?) then
      return nil ;
    else
      time = @timeOrigin + @timeStep * index ;
      return time ;
    end
  end

  #--------------------------------------------------------------
  #++
  ## process individual pedestrian log
  def processIndivLogFile(file, outfile = nil, fillP = false)
    scanIndivLogFile(file) ;
    summarizeGridByTime() ;
    outputSumGridTable(outfile, fillP) ;
  end
    
  #--------------------------------------------------------------
  #++
  ## summarize grid by time
  def summarizeGridByTime()
    @sumGridTable = {} ;
    @gridTable.each{|index, grid|
      (time, posIndex) = index ;
      timeIndex = getTimeIndex(time) ;
      newIndex = [timeIndex, posIndex] ;
      newGrid = @sumGridTable[newIndex] ;
      if(newGrid.nil?) then
        newGrid = Grid.new(self, posIndex, nil, timeIndex) ;
        @sumGridTable[newIndex] = newGrid ;
      end
      newGrid.incPopulation(grid.population) ;
    }
  end
    
  #--------------------------------------------------------------
  #++
  ## output  (old)
  def outputSumGridTable_old(outfile = nil, fillP = false)
    diff = findMinimumTimeDiff() ;
    popUnit = @timeStep / diff ;
    str = CSV.generate{|csv|
      c = 0 ;
      @sumGridTable.keys.sort.each{|index|
        grid = @sumGridTable[index] ;
        csv << grid.genOutputLabelArray() if(c == 0) ;
        c += 1 ;
        csv << grid.genOutputArray(popUnit) ;
      }
    }
    if(outfile.nil?) then
      puts str ;
    else
      open(outfile, "w") { |strm|
        strm << str ;
      }
    end
  end

  #--------------------------------------------------------------
  #++
  ## output
  def outputSumGridTable(outfile = nil, fillP = false)
    diff = findMinimumTimeDiff() ;
    popUnit = @timeStep / diff ;
    str = CSV.generate{|csv|
      c = 0 ;
      (rangeT, rangeX, rangeY, rangeZ) = getIndexRange() ;
      (rangeT[:min]..rangeT[:max]).each{|time|
        (rangeX[:min]..rangeX[:max]).each{|x|
          (rangeY[:min]..rangeY[:max]).each{|y|
            (rangeZ[:min]..rangeZ[:max]).each{|z|
              index = [time, [x,y,z]] ;
              grid = @sumGridTable[index] ;
              if(grid.nil?) then
                if(!fillP) then
                  next ;
                else
                  grid = getDummyGridWithIndex(index) ;
                end
              end
              csv << grid.genOutputLabelArray() if(c == 0) ;
              c += 1 ;
              csv << grid.genOutputArray(popUnit) ;
            }
          }
        }
      }
    }
    if(outfile.nil?) then
      puts str ;
    else
      open(outfile, "w") { |strm|
        strm << str ;
      }
    end
  end

  #--------------------------------------------------------------
  #++
  ## getDummyGridWithIndex
  def getDummyGridWithIndex(index)
    @dummyGrid.timeIndex = index[0] ;
    @dummyGrid.index = index[1] ;
    return @dummyGrid ;
  end

  #--------------------------------------------------------------
  #++
  ## get range of time and XYZ index
  def getIndexRange()
    rangeTime = { :min => nil, :max => nil} ;
    rangeX = { :min => nil, :max => nil} ;
    rangeY = { :min => nil, :max => nil} ;
    rangeZ = { :min => nil, :max => nil} ;
    @sumGridTable.keys.sort.each{|index|
      rangeTime[:min] = safeMin(index[0], rangeTime[:min]) ;
      rangeTime[:max] = safeMax(index[0], rangeTime[:max]) ;
      rangeX[:min] = safeMin(index[1][0], rangeX[:min]) ;
      rangeX[:max] = safeMax(index[1][0], rangeX[:max]) ;
      rangeY[:min] = safeMin(index[1][1], rangeY[:min]) ;
      rangeY[:max] = safeMax(index[1][1], rangeY[:max]) ;
      rangeZ[:min] = safeMin(index[1][2], rangeZ[:min]) ;
      rangeZ[:max] = safeMax(index[1][2], rangeZ[:max]) ;
    }
    return [rangeTime, rangeX, rangeY, rangeZ] ;
  end
    
  #--------------------------------------------------------------
  #++
  ## safeMin
  def safeMin(v, u)
    return ((v.nil?) ?
              u :
              ((u.nil?) ?
                 v :
                 (v > u) ? u : v)) ;
  end

  #--------------------------------------------------------------
  #++
  ## safeMax
  def safeMax(v, u)
    return ((v.nil?) ?
              u :
              ((u.nil?) ?
                 v :
                 (v > u) ? v : u)) ;
  end

  #--------------------------------------------------------------
  #++
  ## find minimum time difference
  def findMinimumTimeDiff()
    pre = nil ;
    diff = nil ;
    @timeNameTable.values.sort.each{|time|
      if(pre.nil?) then
        pre = time ;
      else
        d = time - pre ;
        if(diff.nil? || diff > d) then
          diff = d ;
        end
      end
    }
    return diff ;
  end
    
  #--------------------------------------------------------------
  #++
  ## scan individual pedestrian log
  def scanIndivLogFile(file)
    @csvColumnLabelList = nil ;
    CSV.foreach(file) {|row|
      if(@csvColumnLabelList.nil?) then
        scanFirstRowOfIndividualLogFile(row)
      else
        scanCsvRow(row) ;
      end
    }
  end
    
  #--------------------------------------------------------------
  #++
  ## scan first column
  def scanFirstRowOfIndividualLogFile(row)
    @csvColumnLabelList = [] ;
    @csvColumnIndex = {} ;
    row.each{|val|
      index = @csvColumnLabelList.length ;
      @csvColumnIndex[val] = index ;
      self.instance_variable_set("@index_" + val.to_s, index) ;
      @csvColumnLabelList.push(val) ;
    }
    RequiredColumnName.each{|colName|
      if(!@csvColumnIndex.has_key?(colName)) then
        p [:missingColumn, colName] ;
        raise("log CSV file should have the column: " + colName) ;
      end
    }
  end
    
  #--------------------------------------------------------------
  #++
  ## scan a row of individual pedestrian log
  def scanCsvRow(row)
    return if !checkWalkingAgent(row) ;
    agentId = getAgentIdInCsvRow(row) ;
    time = getCurrentTimeInCsvRow(row) ;
    posIndex = getCurrentPosIndexInCsvRow(row) ;
    index = [time, posIndex] ;
    
    grid = @gridTable[index] ;
    if(grid.nil?) then
      grid = Grid.new(self, posIndex, time) ;
      @gridTable[index] = grid ;
    end

    grid.addAgent(agentId) ;
  end

  #--------------------------------------------------------------
  #++
  ## retrieve a value from CSV row
  def getValueFromCsvRow(row, label)
    return row[@csvColumnIndex[label]] ;
  end

  #--------------------------------------------------------------
  #++
  ## retrieve agent id
  def getAgentIdInCsvRow(row)
#    return getValueFromCsvRow(row, "pedestrianID").intern ;
    return row[@index_pedestrianID].intern ;
  end
  
  #--------------------------------------------------------------
  #++
  ## retrieve a current time from CSV row
  def getCurrentTimeInCsvRow(row)
    timestr = row[@index_current_time] ;
    time = @timeNameTable[timestr] ;
    if(time.nil?) then
      time = parseTime(timestr) ;
      @timeNameTable[timestr] = time ;
    end
    return time ;
  end

  #--------------------------------------------------------------
  #++
  ## retrieve a position from CSV row
  def getCurrentPosInCsvRow(row)
    x = row[@index_current_position_in_model_x].to_f ;
    y = row[@index_current_position_in_model_y].to_f ;
    z = row[@index_current_position_in_model_z].to_f ;
    return [x,y,z] ;
  end

  #--------------------------------------------------------------
  #++
  ## retrieve a position index from CSV row
  def getCurrentPosIndexInCsvRow(row)
    pos = getCurrentPosInCsvRow(row) ;
    index = getPosIndex(pos) ;
    if(@posIndexTable[index].nil?) then
      @posIndexTable[index] = index ;
    end
    return @posIndexTable[index] ;
  end
  
  #--------------------------------------------------------------
  #++
  ## agent alived?
  def checkWalkingAgent(row)
    linkId = row[@index_current_linkID] ;
    return (linkId != "-1") ;
  end
  
  #--============================================================
  #--::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
  #--@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
  #--------------------------------------------------------------
end # class GridTable


########################################################################
########################################################################
########################################################################

gTable = GridTable.new($conf) ;
gTable.processIndivLogFile(ARGV[0], $conf[:outfile], $conf[:fillP]) ;
