#! /usr/bin/env ruby
## -*- mode: ruby -*-
## = Itk Template for Ruby
## Author:: Itsuki Noda
## Version:: 0.0 2015/03/21 I.Noda
##
## === History
## * [2015/03/21]: Create This File.
## * [YYYY/MM/DD]: add more
## == Usage
## * ...

$LOAD_PATH.push("./RubyLib");

require 'optparse' ;
require 'ostruct' ;
require 'pp' ;

require 'ItkXml.rb' ;

#------------------------------------------------------------------------
#++
$conf =
  OpenStruct.new({
                   :foo => false,
                   :bar => 1,
                   :baz => "test",
                 }) ;

#------------------------------------------------------------------------
#++
$op = OptionParser.new() {|op|
  op.banner = <<_END_
  Usage: #{$0} [Options]*
_END_

  op.separator("Options:") ;
  op.set_summary_indent("") ;
  op.set_summary_width(60) ;
  sep = "\n\t\t" ;

  op.on("-f","--[no-]foo", sep + "switch foo.") {|foo|
    $conf.foo = foo ;
  }
  op.on("-b","--bar BarVal", Integer, sep + "bar int value.") {|bar|
    $conf.bar = bar ;
  }
  op.on("-z","--baz BazVal", String, sep + "baz str value.") {|baz|
    $conf.baz = baz ;
  }
  op.on_tail("--help", sep + "show this message.") { |h|
    puts(op)
    exit(1)
  }
}

$op.parse!(ARGV) ;
$restArg = ARGV ;
p [:rest, ARGV], [:conf,$conf] ; 

########################################################################
########################################################################
########################################################################


